### PR TITLE
Elasticsearch updates

### PR DESCRIPTION
**Pull request by AronNovak**
From the latest client project

We should not add stopwords by default, it was a troublemaker for full text search, at least with out of the box views fulltext search.

### CODE REVIEW

**Comment by AronNovak** [comment]
@amitaibu This is the first batch of changes. I plan another PR where I add more safety for user provisioning. With the current code, it's too easy to cause a downtime by creating new password for existing users.

**Comment by amitaibu** [comment]
Thanks

**Comment by amitaibu** [comment]
> With the current code, it's too easy to cause a downtime by creating new password for existing users.

btw, how is the PR changing this?

**Comment by AronNovak** [comment]
@amitaibu It will be covered by the next PR.

**Pull request merged**
