### PR TITLE
Update Drupal to 9.4.5 and contrib modules

### PR DESCRIPTION
**Pull request by amitaibu**
image

<a href="https://gitpod.io/#https://github.com/Gizra/drupal-starter/pull/294"></a>

### CODE REVIEW

**Comment by amitaibu** [comment]
I've uninstalled `ctools`, as it's no longer used by pathauto. However `ddev composer remove drupal/ctools` didn't work

`ddev composer why drupal/ctools` -> `drupal/pathauto 1.11.0 requires drupal/ctools (*)`

**Comment by mariano-dagostino** [comment]
@amitaibu https://www.drupal.org/project/pathauto/releases/8.x-1.11 here is how you can remove the need of ctools.

**Review by mariano-dagostino — CHANGES_REQUESTED** [review]
There is a way to not require ctools. see my last comment.

**Comment by amitaibu** [comment]
image

**Review by mariano-dagostino — APPROVED** [review]

**Pull request merged**
