### PR TITLE
Delete all config translations. And do not pull translations from Drupal on install

### PR DESCRIPTION
**Pull request by mariano-dagostino**
#447

### CODE REVIEW

**Comment by amitaibu** [comment]
Thanks. I'm not sure about this approach - as it's not fixing the root cause, it's only delaying it for implementing projects that would need a multilingual site.

Maybe we could keep the part that skips the import - it makes `ddev restart` faster. But we should keep the language translations, so upon `ddev restart` one we switch to Arabic or Spanish, we'd see the site translated.

**Comment by mariano-dagostino** [comment]
@amitaibu I also tried https://www.drupal.org/files/issues/2023-01-31/2806009-116.patch without success...

it seems some sort of race condition.

1.5h/2 from my side

**Comment by amitaibu** [comment]
@AronNovak care to give it a go? Bump to total 4h

**Comment by AronNovak** [comment]
@amitaibu Sure, especially that https://www.drupal.org/files/issues/2023-01-31/2806009-116.patch was committed to 9.5.x a few days ago

**Comment by AronNovak** [comment]
@amitaibu I finish https://github.com/Gizra/drupal-starter/pull/485 first to have the latest updates in, then I can continue here.

**Comment by AronNovak** [comment]
@amitaibu I think this PR might be good as-is.
For out-of-the-box translations, we have:
https://github.com/Gizra/drupal-starter/tree/main/config/po_files

and a Robo command to import those.
https://github.com/Gizra/drupal-starter/blob/main/.ddev/config.local.yaml.example#L19

I'll make sure those existing PO files are wired properly and has meaningful translations inside.

**Pull request merged**
