### PR TITLE
Migrate default users and content

### PR DESCRIPTION
**Pull request by bboro**
#108 [5h]

## Change summary

* Added `migrate_plus`, `migrate_tools`, `migrate_source_csv` and `migrate_file` modules
* Added custom `server_migrate` module.
   * Adds Tags vocabulary terms
   * Adds a dummy Block Content block
   * Adds demo images from `https://picsum.photos` 
   * Adds dummy users with photo
   * Adds dummy articles with image and tags
   * Adds dummy basic page (Lorem ipsum)
* Set up so that migration runs on restart (If you already have a `.ddev/config.local.yaml` you must regenerate it from the example file to get this to work)

### User profile

User profile

### Articles

article 1

article 2

### Basic page

page

TB: 2 / 5h

### CODE REVIEW

**Review by amitaibu — APPROVED** [review]
Looks great, just a single comment

**Comment by amitaibu** [comment]
Following https://github.com/bboro/drupal-starter/pull/1

- Let's have a total 6 Articles, so we'll have a more meaningful grid
- When editing the node, the Image's alt is empty (but required). So migrate should fill it as-well

**Comment by bboro** [comment]
* Added images locally
* Added 3 more dummy articles
* Added image alts to all articles
   * Note: User images didn't have alt field.

image

TB: 3 / 5h

**Review by amitaibu — APPROVED** [review]
Lovely, thanks

**Comment by AronNovak** [comment]
I am going to adapt the ES-related test to make `master` green.

**Comment by amitaibu** [comment]
Sorry, I missed the red travis!

**Comment by bboro** [comment]
Thanks Aron, sorry :)

**Pull request merged**
