### PR TITLE
Full HTML restrictions

### PR DESCRIPTION
**Pull request by AronNovak**

### CODE REVIEW

**Comment by AronNovak** [comment]
image

Still we are not restricted too much, only `script` and `iframe` should be disabled entirely (on top of `on..` JS event attributes)

**Comment by AronNovak** [comment]
@amitaibu What do you think? Is it overly specific or ugly to be included? Do you generally agree that we should do something with Full HTML to exclude known dangerous stuff?

**Comment by amitaibu** [comment]
@AronNovak what did you use to get the list of allowed HTML values?

**Comment by AronNovak** [comment]
AFAIK https://www.w3schools.com/tags/default.asp and https://www.w3schools.com/tags/ref_attributes.asp

**Pull request merged**
