### PR TITLE
WIP: Bump ElasticSearch to latest stable

### PR DESCRIPTION
**Pull request by AronNovak**
<a href="https://gitpod.io/#https://github.com/Gizra/drupal-starter/pull/244"></a>

### CODE REVIEW

**Comment by AronNovak** [comment]
As well to see if https://github.com/drud/ddev-elasticsearch can be bumped too.

**Comment by amitaibu** [comment]
Travis seems red :)

**Comment by AronNovak** [comment]
@amitaibu That's right, the infra part is more or less ready, but the integration module also needs some love for that.

**Comment by AronNovak** [comment]
https://www.drupal.org/project/elasticsearch_connector/issues/3279558
Perhaps it gets noticed.

**Pull request closed without merging**
