### PR TITLE
Deployment exclusions

### PR DESCRIPTION
**Pull request by AronNovak**

### CODE REVIEW

**Comment by AronNovak** [comment]
Seen a strange deployment changeset...

**Comment by AronNovak** [comment]
ping

**Comment by amitaibu** [comment]
I think this had to do with a TW v1 installation we had. I think we should not merge this, since we're no longer supporting that version. Is it ok if I close, or do you think I'm missing your point?

**Comment by AronNovak** [comment]
It's okay, that client project did use TW v1 almost certainly.

**Pull request closed without merging**
