### PR TITLE
Refactor code for the new changes in PEVB 1.1.4

### PR DESCRIPTION
**Pull request by bboro**
PEVB may get ElementWrapTrait in 1.1.3 (or 1.1.4) instead of ComponentWrapTrait with slightly changed method parameters. 

Refactored while I was working on the module, so may as well push the changes in prep for the module update.

WIP until module is updated.

### CODE REVIEW

**Comment by amitaibu** [comment]
https://github.com/Gizra/drupal-starter/pull/160/commits/3f40f2b5afb3745a92ebfc2d906eb6282ac575fb Will show correct background image (with image style) once https://www.drupal.org/project/pluggable_entity_view_builder/issues/3215579 is merged

**Comment by amitaibu** [comment]
Travis currently fails due to the PEVB Mr not merged yet. Good job PHPstan :)

image

**Comment by bboro** [comment]
https://git.drupalcode.org/project/pluggable_entity_view_builder/-/merge_requests/6#note_26807 is merged now.

**Comment by amitaibu** [comment]
Thanks. It will require a minor release to PEVB. I'll do it later

**Comment by amitaibu** [comment]
New version for PEVB - https://www.drupal.org/project/pluggable_entity_view_builder/releases/1.1.4

**Pull request merged**
