### PR TITLE
Upgrade to ddev 1.17

### PR DESCRIPTION
**Pull request by amitaibu**
cc @AronNovak

### CODE REVIEW

**Comment by AronNovak** [comment]
@amitaibu Pushed a missing bit, looks good otherwise!

**Review by AronNovak — APPROVED** [review]

**Comment by amitaibu** [comment]
@AronNovak I'm looking at https://github.com/drud/ddev/blob/master/cmd/ddev/cmd/dotddev_assets/providers/pantheon.yaml.example and I think we need to approach the pantheon auth differently. I'll try it out

**Comment by amitaibu** [comment]
Yeah, I think we'd like to restructure a bit our Robofile, for example instead of defining the Pantheon site name directly in it, we'd extract that info from the [yaml](https://github.com/drud/ddev/blob/e702a98080b459e3fd7742e27dd3400ad46fe5bc/cmd/ddev/cmd/dotddev_assets/providers/pantheon.yaml.example#L40) file

**Comment by amitaibu** [comment]
@AronNovak Marking as needs review, since I think #151 can be added as a follow up

**Review by AronNovak — APPROVED** [review]
Just corrected the syntax for `auth:login`, all good otherwise.

**Comment by amitaibu** [comment]
Thanks

**Pull request merged**
