### PR TITLE
Prevent deletion/unpublish of "locked" landing pages

### PR DESCRIPTION
**Pull request by andreytroeglazov**
#308 

- Installed Config Pages
- Installed Admin toolbar
- Created Main settings config page
- Created Locked landing pages field
- Created migration for Homepage
- Adjusted content editor permissions
- Restricted deletion/unpublishing on locked nodes
- Removed delete button and status checkbox from node form

Todo:
- Add message
- Add test

TB: 4 / 3 (spent much time on migration config pages)

### CODE REVIEW

**Comment by andreytroeglazov** [comment]
@amitaibu I will need a small bump to cover todo points.

Will provide a video with example later.

**Comment by amitaibu** [comment]
Sure, 2h bump

**Comment by bboro** [comment]
This PR opened a year ago :) Is this still valid?

**Comment by andreytroeglazov** [comment]
@bboro sorry, I have forgot about this one, will finish asap.

**Comment by bboro** [comment]
No rush @andreytroeglazov was just going through the PRs

**Comment by amitaibu** [comment]
We had a case on a client project where a landing page should have been locked. Let's revive this PR :)

**Comment by andreytroeglazov** [comment]
Video:
https://github.com/Gizra/drupal-starter/assets/81006789/8269212a-5130-4788-80ac-adc9733efb1f
Config page:
Selection_1337

Took more time to deal with default content, resolve merge conflicts and remove `delete` link from other places for locked nodes + test.

TB total: 7.7h

**Review by amitaibu — APPROVED** [review]
Looks good, thanks :pray:

**Pull request merged**
