### PR TITLE
Squash and merge-compatible release notes generator

### PR DESCRIPTION
**Pull request by AronNovak**
#412 

## Status
image

### CODE REVIEW

**Comment by AronNovak** [comment]
a changelog:

## Changelog
- Memory limit also affects PHPunit tests (#383)
  - * memory limit for cli (#409)


## Contributors
- @AronNovak (1)
- @mariano-dagostino (1)


## Code statistics
- Lines added: 8
- Lines deleted: 0
- Files changed: 1

**Review by bboro — APPROVED** [review]

**Comment by bboro** [comment]
This githubapi implementation keeps returning 404 locally for me, I guess I'm missing the access to Gizra org's repos with my key... Are you using a token from your account or from Gizra?

**Comment by AronNovak** [comment]
@bboro 
https://github.com/settings/tokens/new
image

**Comment by amitaibu** [comment]
Maybe worth mentioning the info about the token in the README.

**Comment by AronNovak** [comment]
@amitaibu 
image
It was already there. as we used GH API already, but now, we started to fetch data about the pull request too.

**Pull request merged**
