### PR TITLE
DOS check Robo command

### PR DESCRIPTION
**Pull request by AronNovak**
#601 

## Status

New commands:
```
 security
  security:access-log-overview     Analyze security access log interactively.
  security:check-ddos              Checks DDOS attacks by identifying top requester IP addresses.
```

### CODE REVIEW

**Comment by AronNovak** [comment]
```
 aaron   601-dos-check  ~  gizra  drupal-starter  ddev robo security:check-ddos qa 6
 [Exec] Running $(terminus connection:info --field=sftp_command gizra-drupal-starter.qa) <<EOF
cd logs/nginx
get nginx-access.log /tmp/nginx-access.log
EOF
Connected to appserver.qa.5acc1750-abf0-47ef-a6d8-6890a6efaca8.drush.in.
sftp> cd logs/nginx
sftp> get nginx-access.log /tmp/nginx-access.log
Fetching /logs/nginx/nginx-access.log to /tmp/nginx-access.log
/logs/nginx/nginx-access.log                                                                                                   100%  173KB 193.0KB/s   00:00    
 [Exec] Done in 10.482s
| Count | IP Address | Host | % of Total Requests |
|-------|------------|------|---------------------|
| 204 | 82.66.214.47 | men75-2_migr-82-66-214-47.fbx.proxad.net | 45.84% |
| 90 | 20.7.221.176 | 20.7.221.176 | 20.22% |
| 45 | 2a0a:f640:1601:a870:9871:6479:81fc:5b8d | 2a0a:f640:1601:a870:9871:6479:81fc:5b8d | 10.11% |
| 43 | 2001:4c4e:1e9d:3200:9afe:a5c9:9d2d:6ff5 | 20014C4E1E9D32009AFEA5C99D2D6FF5.dsl.pool.telekom.hu | 9.66% |
| 19 | 2001:4c4e:1ea1:7e00:10a9:af44:d6ed:a7f1 | 20014C4E1EA17E0010A9AF44D6EDA7F1.dsl.pool.telekom.hu | 4.27% |
| 12 | 52.27.98.123 | ec2-52-27-98-123.us-west-2.compute.amazonaws.com | 2.7% |
```

**Comment by AronNovak** [comment]
```
 aaron   601-dos-check  ~  gizra  drupal-starter  ddev robo security:check-ddos qa 3
 [Exec] Running $(terminus connection:info --field=sftp_command gizra-drupal-starter.qa) <<EOF
cd logs/nginx
get nginx-access.log /tmp/nginx-access.log
EOF
Connected to appserver.qa.5acc1750-abf0-47ef-a6d8-6890a6efaca8.drush.in.
sftp> cd logs/nginx
sftp> get nginx-access.log /tmp/nginx-access.log
Fetching /logs/nginx/nginx-access.log to /tmp/nginx-access.log
/logs/nginx/nginx-access.log                                                                                                   100%  173KB 195.5KB/s   00:00    
 [Exec] Done in 9.281s
| Count | IP Address | Host | % of Total Requests |
|-------|------------|------|---------------------|
| 204 | 82.66.214.47 | men75-2_migr-82-66-214-47.fbx.proxad.net | 45.84% |
| 90 | 20.7.221.176 | 20.7.221.176 | 20.22% |
| 45 | 2a0a:f640:1601:a870:9871:6479:81fc:5b8d | 2a0a:f640:1601:a870:9871:6479:81fc:5b8d | 10.11% |
```

```
ddev robo security:access-log-overview qa
```
image

**Review by amitaibu — APPROVED** [review]
Thanks

**Comment by AronNovak** [comment]
@mariano-dagostino Done, if syntax would change, it can come handy.

**Pull request merged**
