### PR TITLE
PHP 8 upgrade

### PR DESCRIPTION
**Pull request by AronNovak**

### CODE REVIEW

**Comment by AronNovak** [comment]
image

**Comment by AronNovak** [comment]
image

**Comment by amitaibu** [comment]
Nothing else needed here?

**Comment by AronNovak** [comment]
@amitaibu nope, time solved the challenging parts.

**Comment by amitaibu** [comment]
I think there's a yaml on Pantheon's site to indicate which PHP version. I think we should have it here as part of the repo

**Comment by AronNovak** [comment]
@amitaibu That's a great suggestion, managing `settings.php` was in the very same direction.

**Pull request merged**
