### PR TITLE
Use upstream Pluggable entity view builder module

### PR DESCRIPTION
**Pull request by amitaibu**
https://www.drupal.org/project/pluggable_entity_view_builder

### CODE REVIEW

**Comment by amitaibu** [comment]
Here's how an article will be rendered. So it looks similar to how it does now, only with less custom code

image

**Comment by amitaibu** [comment]
Blocked by https://gitlab.com/drupalspoons/pluggable_entity_view_builder/-/merge_requests/10

**Comment by amitaibu** [comment]
@bboro helper for reviewing:

- make sure to update `config.local.yaml` with the new `drush cr` in the end of the install
- Create a new article node with an image, and some tags
- Witness the glory of Pluggable entity view builders :wink:

**Review by bboro — APPROVED** [review]
@amitaibu this works well and looks good to me. A couple points not directly related to the PR:

* Hero image looks stretched on articles. I'll push a quick PR for this. https://github.com/Gizra/drupal-starter/pull/76
* Preview for "Teaser" view mode produces 500 error when the node's being created. This is due to us trying to `->id()` or `->toUrl()` the node when it doesn't have an ID yet. This probably belongs on the Pluggable entity builder module.

Approved :+1: 

TB: +0.5h

**Comment by amitaibu** [comment]
> Preview for "Teaser" view mode produces 500 error 

Good catch. I'll look into it

**Comment by amitaibu** [comment]
> Preview for "Teaser" view mode produces 500

What are the steps to reproduce?

**Comment by amitaibu** [comment]
@bboro ^^

**Comment by bboro** [comment]
@amitaibu Sorry missed that. 

Try this:
1. Create new Article and fill in all fields ( I think maybe uploading an image causes this - so upload a preview image too)
2. Click "Preview" without hitting Save
3. Select "Teaser" view mode from the view mode selector on the preview page.
^ that should produce the error.

**Comment by amitaibu** [comment]
Got it, thanks. Issue is then coming from this PR (where the `NodeArticle` plugin is implemented). I'll adapt

**Review by bboro — APPROVED** [review]
:+1:

**Comment by amitaibu** [comment]
fyi, Created a PR to fix also the example module of the module - https://gitlab.com/drupalspoons/pluggable_entity_view_builder/-/merge_requests/11

**Pull request merged**
