### PR TITLE
Issue-726: Theming the default contact form.

### LINKED ISSUE #726: Theming the default contact form [3h]
### Issue

`/contact`

Screenshot 2024-09-25 at 10 39 22

### PR DESCRIPTION
**Pull request by sonvir249**
## Closes #726 
Contact form after styling: 
image

### CODE REVIEW

**Comment by sonvir249** [comment]
First time tried hands on CSS 🙈, please do let me know if any changes needed. I am here to learn and grow.

**Comment by amitaibu** [comment]
Thanks. Let's see if we can avoid special-casing the Contact form. In fact, I think we should remove this Contact form and replace it with integration with Webform.

@mgurjanov I think you have done something like this in the past -- allowing embedding webforms inside Langing pages. Would you mind giving some poonters?

**Comment by mgurjanov** [comment]
@amitaibu Yes I did implement this. I installed webform, created Paragraph type that allows referencing Webforms and I wired and styled this paragraph. There is also common styling for all such webforms that gets applied to any paragraph webform. This paragraph can then be enabled on Landing page CT. It was a bit larger PR but most of the files are originating from enabling Webform module. So, there is PEVB plugin and there is buildWebformEmbed() within FormsEmbedTrait and finally form.pcss. I also had optional Title and Description fields that could be rendered with the webform. Of course there are some config options for Webform itself and permissions etc.

**Comment by amitaibu** [comment]
@mgurjanov Seems we've already solved most of it already, so maybe you'd like to tackle it?

@sonvir249 you could help with the review! 🙏

**Comment by mgurjanov** [comment]
@amitaibu Yes I will work on it.

**Comment by sonvir249** [comment]
Closing this PR in favour of #759 
cc: @amitaibu @mgurjanov

**Pull request closed without merging**
