### PR TITLE
Improve the styleguide UX

### PR DESCRIPTION
**Pull request by bboro**

### CODE REVIEW

**Comment by bboro** [comment]
- Stop clicks on styleguide titles jumping the page (event.preventDefault()).
- Initialize slick sliders when they're expanded
- Allow elements to be opened and closed instead of having only 1 element open. This combined with point 1 also stops the clicks on titles triggering the page scrolling, which can trigger some header behaviors etc.

**Review by amitaibu — APPROVED** [review]
Thanks :+1:

**Comment by bboro** [comment]
@amitaibu don't merge yet, noticed we don't have slick on drupal-starter by default.

**Comment by bboro** [comment]
- Disabled advagg on ddev
- Restored hiding all panels on styleguide on load
- Added detection of slick library before attempting to call it.

**Comment by bboro** [comment]
- Update the URL hash when titles are clicked (this was disabled by `event.preventDefault()`) - @andreytroeglazov thanks for highlighting this and sorry for not understanding what you meant :D

**Pull request merged**
